/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type ScorecardVersion = "1";
export type FilenameForCIYaml = string;
export type InfrastructureAsCode = boolean;
export type MessagingChannel = string;
export type MessagingChannelsIntegrated = MessagingChannel[];
export type AutomatedConversationTags = null;
export type CodeAndTrainingDataIsInGit = boolean;
export type RasaTestCoverage = number;
export type CIRunsDataValidation = boolean;
export type CIRunsRasaTest = boolean;
export type CITrainsAModel = boolean;
export type CIBuildsAnActionServer = boolean;
export type CIRunsVulnerabilityScans = boolean;
export type NumberOfRealConversations = number;
export type NumberOfAnnotatedMessages = number;
export type NumberOfWarningsFromNLUInsights = number;
export type NumberOfReviewedConversations = number;
export type NumberOfTaggedConversations = number;

export interface RasaAssistantScorecard {
  version: ScorecardVersion;
  scorecard: Scorecard;
}
export interface Scorecard {
  manual: ManualMetrics;
  auto: AutomaticScorecard;
}
export interface ManualMetrics {
  CI: ManualCIScorecard;
  CD: ManualCDScorecard;
  training_data_health?: ManualTrainingDataHealthScorecard;
  success_kpis: ManualSuccessKPIsScorecard;
}
export interface ManualCIScorecard {
  filename: FilenameForCIYaml;
}
export interface ManualCDScorecard {
  infrastructure_as_code: InfrastructureAsCode;
  messaging_channels_integrated: MessagingChannelsIntegrated;
}
export interface ManualTrainingDataHealthScorecard {}
export interface ManualSuccessKPIsScorecard {
  automated_conversation_tags: AutomatedConversationTags;
}
export interface AutomaticScorecard {
  CI: AutomaticCIScorecard;
  CD?: AutomaticCDScorecard;
  training_data_health: AutomaticTrainingDataHealthScorecard;
  success_kpis: AutomaticSuccessKPIsScorecard;
}
export interface AutomaticCIScorecard {
  code_and_training_data_in_git: CodeAndTrainingDataIsInGit;
  rasa_test_coverage: RasaTestCoverage;
  ci_runs_data_validation: CIRunsDataValidation;
  ci_runs_rasa_test: CIRunsRasaTest;
  ci_trains_model: CITrainsAModel;
  ci_builds_action_server: CIBuildsAnActionServer;
  ci_runs_vulnerability_scans: CIRunsVulnerabilityScans;
}
export interface AutomaticCDScorecard {}
export interface AutomaticTrainingDataHealthScorecard {
  num_real_conversations: NumberOfRealConversations;
  num_annotated_messages: NumberOfAnnotatedMessages;
  num_warnings_from_nlu_insights: NumberOfWarningsFromNLUInsights;
}
export interface AutomaticSuccessKPIsScorecard {
  num_reviewed_conversations: NumberOfReviewedConversations;
  num_tagged_conversations: NumberOfTaggedConversations;
}
